branch-defaults:
  main:
    environment: null
    group_suffix: null
  master:
    environment: Classicmodels-backend-env
deploy:
  artifact: ./build/libs/classicmodels-0.0.2-SNAPSHOT.jar
environment-defaults:
  Vue8-env:
    branch: null
    repository: null
global:
  application_name: Classicmodels-backend
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
